/**
 * PlanMejora.js
 * Fuente operativa del Plan de Mejora Institucional 2026-2027.
 * Basado en IAI 2025, versión sancionada, pp. 54-67.
 * Los campos de seguimiento se almacenan en PropertiesService para la versión de prueba.
 */

const PLAN_MEJORA_2026_2027 = [
  ['PM-001','Docencia y Resultados del Proceso Formativo','Oferta formativa','P2','2026-05','2026-08','Aplicar y consolidar el Procedimiento institucional de Oferta Formativa Anual para la oferta 2027, verificando su trazabilidad documental y su articulación con benchmarking, matrícula, capacidad instalada, dotación docente, convenios y observaciones CNED.','Procedimiento plenamente aplicado y trazable para la oferta 2027.','100% del procedimiento aplicado con expediente completo, acta del Comité y resolución de Rectoría.','Procedimiento vigente; benchmarking 2022-2026; acta; resolución; propuesta de oferta 2027.','CLP 0,8 MM + HH internos.','Rectoría / Dirección Docente / DAC',0.8],
  ['PM-002','Docencia y Resultados del Proceso Formativo','Oferta formativa','P2','2027-04','2027-10','Ejecutar el ciclo anual de oferta 2028, incluyendo análisis comparado por territorio y carrera, revisión de vacantes, capacidad instalada y sustentabilidad académica y financiera.','Oferta 2028 fundada técnicamente y sancionada en plazo.','1 informe anual completo, 1 acuerdo colegiado y 1 resolución emitidos en plazo.','Informe de oferta 2028; benchmarking; nómina docente; inventarios; actas; resolución.','CLP 0,6 MM + HH internos.','Rectoría / Dirección Docente / DAC / DAF',0.6],
  ['PM-003','Docencia y Resultados del Proceso Formativo','Modelo formativo y perfiles de ingreso y egreso','P2','2026-05','2026-11','Consolidar el cierre formal del ciclo de revisión curricular en carreras en régimen, mediante versionado, resolución, cohorte de vigencia y cierre de observaciones derivadas del análisis de perfiles, matrices y estudios de pertinencia/coherencia.','100% de carreras en régimen con expediente curricular formalizado.','100% de carreras con informe, matriz, acta, resolución y vigencia definida.','Informes; matrices; actas; resoluciones; versiones actualizadas.','CLP 4,0 MM + HH internos y eventual asesoría.','Dirección Docente / UDIC / DAC',4.0],
  ['PM-004','Docencia y Resultados del Proceso Formativo','Modelo formativo y perfiles de ingreso y egreso','P2','2027-03','2027-11','Auditar la consistencia entre modelo formativo, programas, syllabus y evaluaciones integradas, incorporando ajustes curriculares priorizados por carrera.','Consistencia curricular institucional superior al 90%.','Al menos 90% sin desviaciones críticas y plan de corrección cerrado para el resto.','Informe de auditoría curricular; planillas de control; versiones ajustadas.','CLP 2,0 MM + HH internos.','Dirección Docente / UDIC / DAC',2.0],
  ['PM-005','Docencia y Resultados del Proceso Formativo','Acceso y progresión de los estudiantes','P2','2026-04','2026-12','Consolidar el uso institucional de SIGA v1.0 para monitoreo agregado de asistencia, calificaciones y alertas tempranas en ambas sedes, formalizando protocolos de derivación académica, socioeconómica y administrativa.','Sistema operando institucionalmente con protocolos aplicados en 100% de carreras en régimen.','100% de carreras con monitoreo activo; reportes mensuales y seguimiento documentado.','Protocolos; reportes SIGA; actas; registros de tutorías, ayudas y derivaciones.','CLP 3,5 MM + HH internos y soporte TI.','Dirección Docente / DAE / DAC / TI / DAF',3.5],
  ['PM-006','Docencia y Resultados del Proceso Formativo','Acceso y progresión de los estudiantes','P2','2027-03','2027-11','Evaluar el impacto del sistema de alerta temprana sobre retención, aprobación y asistencia, ajustando umbrales y apoyos por sede y carrera.','Informe anual de impacto y plan de ajuste 2028 implementado.','Informe emitido; mejora o estabilización favorable en al menos 2 indicadores críticos.','Informe de impacto; dashboard comparado; actas; plan de ajuste.','CLP 1,5 MM + HH internos.','DAC / Dirección Docente / DAE / TI',1.5],
  ['PM-007','Docencia y Resultados del Proceso Formativo','Empleabilidad','P3','2026-05','2026-10','Consolidar la base institucional de titulados y estandarizar la medición anual de empleabilidad y trayectoria por carrera y cohorte, utilizando el Portal de Titulados ya habilitado como soporte operativo.','Base institucional activa y primer informe comparable de empleabilidad emitido.','Al menos 60% de titulados recientes contactados y reporte para 100% de carreras con titulados.','Portal operativo; base de datos; encuestas; informe de empleabilidad; reportes por carrera.','CLP 1,2 MM + HH internos y mantención portal.','DICOVIM / DAC / Dirección Docente',1.2],
  ['PM-008','Docencia y Resultados del Proceso Formativo','Empleabilidad','P3','2027-04','2027-10','Implementar un circuito anual de retroalimentación con titulados y empleadores para traducir resultados de empleabilidad a ajustes curriculares y de Vinculación con el Medio.','Retroalimentación incorporada al menos en 70% de las carreras con titulados.','Al menos 70% de carreras con acta de retroalimentación o ajuste.','Actas; informes de empleadores; minutas; ajustes curriculares.','CLP 1,5 MM + HH internos.','DICOVIM / Dirección Docente / UDIC / DAC',1.5],
  ['PM-009','Docencia y Resultados del Proceso Formativo','Cuerpo docente','P2','2026-04','2026-08','Verificar y asegurar la aplicación institucional del perfil docente por asignatura, junto con la inducción y evaluación docente semestral, sistematizando brechas y acciones de mejora por carrera.','100% de asignaturas con perfil docente aplicable y evaluación semestral ejecutada.','100% de asignaturas con perfil; al menos 90% de docentes evaluados cada semestre.','Perfiles docentes; nóminas; instrumentos; informes semestrales; actas.','CLP 2,5 MM + HH internos y soporte TI.','Dirección Docente / RR.HH. / DAC',2.5],
  ['PM-010','Docencia y Resultados del Proceso Formativo','Cuerpo docente','P2','2027-03','2027-11','Implementar un plan de desarrollo docente focalizado en RAA, evaluación, acompañamiento en aula y estabilización de capacidades críticas por carrera.','Plan anual ejecutado con cobertura mínima de 80% del cuerpo docente activo.','Cobertura igual o superior a 80% y reducción de brechas críticas observadas en evaluación docente.','Plan de capacitación; asistencia; informes de evaluación; renovaciones; reportes por carrera.','CLP 3,0 MM + HH internos y relatorías externas.','Dirección Docente / RR.HH. / DAC / Rectoría',3.0],
  ['PM-011','Gestión Estratégica y Recursos Institucionales','Gobierno y estructura organizacional','P1','2026-05','2026-09','Verificar, armonizar y dejar trazable la concordancia entre reglamentos, organigrama, descriptor de cargos, calendario de cuerpos colegiados y matriz de seguimiento de acuerdos.','Marco de gobierno concordante y operativo para 2026-2.','100% de instrumentos clave concordados y calendario colegiado operando.','Reglamentos; organigrama; descriptor; calendario; actas; resoluciones.','CLP 0,6 MM + HH internos y revisión técnica.','Rectoría / DAC / DAF',0.6],
  ['PM-012','Gestión Estratégica y Recursos Institucionales','Gobierno y estructura organizacional','P1','2027-03','2027-11','Evaluar la funcionalidad de la estructura y la ejecución de acuerdos estratégicos, incorporando un reporte anual de gobernanza.','Reporte anual de gobernanza emitido y plan de ajuste 2028 definido.','1 reporte anual emitido y al menos 80% de acuerdos con seguimiento documentado.','Reporte de gobernanza; actas; cuadro de seguimiento; plan de ajuste.','CLP 0,4 MM + HH internos.','Rectoría / DAC / Secretaría de cuerpos colegiados',0.4],
  ['PM-013','Gestión Estratégica y Recursos Institucionales','Gestión y desarrollo de personas','P1','2026-04','2026-10','Digitalizar y fortalecer el ciclo de reclutamiento, inducción, evaluación y capacitación de personal directivo, docente y administrativo.','Sistema de RR.HH. con trazabilidad completa para evaluación y capacitación.','Al menos 90% de expedientes completos y 100% del personal nuevo con inducción formal.','Expedientes; matriz de capacitación; informes de evaluación; registros de inducción.','CLP 1,8 MM + HH internos y soporte TI.','RR.HH. / DAF / DAC',1.8],
  ['PM-014','Gestión Estratégica y Recursos Institucionales','Gestión y desarrollo de personas','P1','2027-03','2027-11','Implementar un plan de retención y desarrollo de capacidades críticas, con foco en jefaturas, funciones tácticas y personal académico clave.','Plan de retención aplicado a cargos críticos definidos institucionalmente.','Al menos 80% de cargos críticos con estrategia definida y seguimiento anual.','Mapa de cargos críticos; planes individuales; reportes de seguimiento.','CLP 2,0 MM + HH internos, incentivos y capacitación.','Rectoría / RR.HH. / Dirección Docente / DAF',2.0],
  ['PM-015','Gestión Estratégica y Recursos Institucionales','Gestión de recursos','P1','2026-04','2026-12','Ejecutar el Plan de Inversiones 2026, priorizando laboratorios, talleres, biblioteca, espacios de estudio, software y equipamiento computacional según estándares por carrera.','Ejecución anual 2026 del plan con avance físico y presupuestario verificado.','Ejecución igual o superior a 85% y evidencia de habilitación de ítems prioritarios.','Plan de inversiones; órdenes de compra; inventarios; actas; registros fotográficos.','CLP 35,0 MM + HH internos.','DAF / Dirección Docente / TI / DAC',35.0],
  ['PM-016','Gestión Estratégica y Recursos Institucionales','Gestión de recursos','P1','2027-03','2027-11','Ejecutar el Plan de Inversiones 2027 y consolidar el seguimiento de diversificación de ingresos como apoyo al cierre de brechas.','Cierre anual 2027 con reporte integrado de inversiones y recursos complementarios.','Ejecución igual o superior a 85% y al menos 1 reporte anual integrado.','Informe anual de inversiones; inventarios; informe OTEC; reporte CEIL.','CLP 39,0 MM + HH internos.','DAF / Rectoría / DAC / OTEC-CEIL',39.0],
  ['PM-017','Gestión Estratégica y Recursos Institucionales','Convivencia, equidad de género, diversidad e inclusión','P1 / P2','2026-05','2026-10','Sistematizar y evidenciar la aplicación institucional de la política de inclusión, mecanismos de convivencia y protocolos de resguardo de derechos, fortaleciendo la trazabilidad de derivaciones, apoyos, adecuaciones razonables, casos atendidos y acciones de difusión en ambas sedes.','Sistema institucional de registro, trazabilidad y reporte anual operando en ambas sedes.','100% de mecanismos vigentes aplicados con respaldo documental y 1 reporte anual consolidado emitido.','Política de inclusión; protocolo 21.369 y normativa asociada; piezas de difusión; registros de casos, derivaciones y adecuaciones; reporte anual.','CLP 1,0 MM + HH internos y jornadas de difusión.','DAE / DAC / Dirección Docente',1.0],
  ['PM-018','Gestión Estratégica y Recursos Institucionales','Convivencia, equidad de género, diversidad e inclusión','P1 / P2','2027-03','2027-11','Evaluar anualmente resultados, oportunidad de respuesta y percepción estudiantil en convivencia, inclusión, bienestar y resguardo de derechos, utilizando los hallazgos para definir ajustes institucionales 2028.','Reporte anual emitido y plan de ajuste 2028 definido.','1 reporte anual emitido, al menos 80% de casos cerrados dentro de plazo y plan de ajuste aprobado.','Reporte anual; base de casos; encuestas; actas; plan de ajuste.','CLP 0,8 MM + HH internos.','DAE / DAC / Rectoría',0.8],
  ['PM-019','Aseguramiento Interno de la Calidad','Gestión y resultados del aseguramiento interno de la calidad','P1','2026-04','2026-12','Operacionalizar el SAC 2025 mediante tablero institucional de indicadores, calendario de seguimiento y reportes periódicos de brechas y acciones de mejora.','Sistema de seguimiento institucional operando con periodicidad definida.','Al menos 4 reportes institucionales emitidos en 2026 y 100% de indicadores críticos actualizados.','Dashboard; reportes trimestrales; actas; matrices de seguimiento.','CLP 1,5 MM + HH internos y soporte TI/BI.','DAC / TI / Rectoría',1.5],
  ['PM-020','Aseguramiento Interno de la Calidad','Gestión y resultados del aseguramiento interno de la calidad','P1','2027-03','2027-11','Cerrar ciclos de mejora por dimensión y criterio, verificando cumplimiento de acciones, uso de resultados y ajustes institucionales 2027.','Ciclos de mejora cerrados en criterios priorizados y reportados.','Al menos 75% de acciones 2026-2027 cerradas con evidencia, evaluación y decisión posterior documentada.','Informes de cierre; matrices de seguimiento; actas.','CLP 1,0 MM + HH internos.','DAC / Rectoría / Direcciones de área',1.0],
  ['PM-021','Aseguramiento Interno de la Calidad','Aseguramiento de la calidad de los programas formativos','P2','2026-05','2026-10','Aplicar un ciclo anual de revisión de programas formativos por carrera, considerando programas, syllabus, perfiles de egreso, matrices de tributación y ESI.','100% de carreras en régimen revisadas bajo un estándar común.','100% de carreras revisadas; expedientes completos y observaciones críticas con plan de corrección.','Expedientes por carrera; informes de revisión; matrices; actas; versiones ajustadas.','CLP 3,0 MM + HH internos y apoyo UDIC.','Dirección Docente / UDIC / DAC',3.0],
  ['PM-022','Aseguramiento Interno de la Calidad','Aseguramiento de la calidad de los programas formativos','P2','2027-03','2027-11','Auditar la aplicación institucional del estándar curricular y evaluativo, verificando consistencia entre carreras, sedes y jornadas.','Informe de auditoría institucional emitido y plan de cierre de observaciones ejecutado.','Al menos 85% de carreras/sedes auditadas sin observaciones críticas y plan de cierre para el resto.','Informe de auditoría; listas de chequeo; planes de corrección; actas.','CLP 2,0 MM + HH internos.','DAC / Dirección Docente / UDIC',2.0],
  ['PM-023','Aseguramiento Interno de la Calidad','Integridad institucional','P1','2026-05','2026-08','Armonizar, difundir y dejar trazable el marco de integridad institucional, incluyendo código de ética, conflictos de interés, buen trato, Ley 21.369 y canales de denuncia.','Marco de integridad armonizado, difundido y con registro de cobertura.','100% de instrumentos clave armonizados y al menos 80% de cobertura en difusión a estamentos prioritarios.','Código de ética; declaraciones; piezas de difusión; registros de participación; protocolo 21.369.','CLP 0,7 MM + HH internos, difusión y capacitación.','Rectoría / DAC / DAE / RR.HH.',0.7],
  ['PM-024','Aseguramiento Interno de la Calidad','Integridad institucional','P1','2027-03','2027-11','Implementar monitoreo anual de integridad, conflictos de interés y respuesta institucional a requerimientos o denuncias, con reporte 2027.','Reporte anual de integridad emitido y mejoras implementadas.','1 reporte anual emitido, tiempos de respuesta dentro de protocolo y plan de mejora aplicado.','Reporte anual; registros de casos; actas; plan de mejora.','CLP 0,6 MM + HH internos.','DAC / Rectoría / DAE / RR.HH.',0.6],
  ['PM-025','Vinculación con el Medio','Política y gestión de la vinculación con el medio','P3','2026-05','2026-09','Operacionalizar la Política y el Plan Anual de Vinculación con el Medio 2026-2027, priorizando redes por carrera, uso efectivo de convenios, prácticas, formación continua y transferencia técnica.','Política y plan operacionalizados con líneas activas por carrera.','Política y plan en ejecución y al menos 1 línea activa de VcM por carrera en régimen.','Política; plan anual; convenios; actas; programación de actividades.','CLP 1,2 MM + HH internos y gestión territorial.','DICOVIM / Dirección Docente / Rectoría',1.2],
  ['PM-026','Vinculación con el Medio','Política y gestión de la vinculación con el medio','P3','2027-03','2027-11','Consolidar la cartera institucional de convenios y actividades bidireccionales, incorporando seguimiento de uso efectivo por carrera y sede.','Matriz de convenios y uso efectivo con reporte anual 2027.','Al menos 70% de convenios prioritarios con uso efectivo documentado.','Matriz de convenios; reportes de uso; actas; informes de actividades.','CLP 1,5 MM + HH internos y gestión externa.','DICOVIM / Jefaturas de carrera / DAC',1.5],
  ['PM-027','Vinculación con el Medio','Resultados e impacto de la vinculación con el medio','P3','2026-06','2026-12','Definir e implementar indicadores de resultados e impacto de la Vinculación con el Medio, articulando convenios, prácticas, titulados, empleadores y formación continua.','Batería institucional de indicadores operativa y primer reporte de resultados emitido.','Batería aprobada y 1 reporte de resultados emitido al cierre de 2026.','Matriz de indicadores; reportes; bases de datos; actas.','CLP 0,9 MM + HH internos y apoyo analítico.','DICOVIM / DAC / Dirección Docente',0.9],
  ['PM-028','Vinculación con el Medio','Resultados e impacto de la vinculación con el medio','P3','2027-03','2027-11','Emitir el primer informe institucional de impacto de Vinculación con el Medio y usar sus resultados para retroalimentar empleabilidad, prácticas y revisión curricular.','Informe institucional de impacto emitido y utilizado en decisiones académicas.','1 informe de impacto emitido y al menos 3 decisiones institucionales o curriculares respaldadas en sus resultados.','Informe de impacto; actas; ajustes curriculares; reportes de empleabilidad y prácticas.','CLP 1,2 MM + HH internos y levantamiento de información.','DICOVIM / DAC / Dirección Docente / UDIC',1.2]
];

function obtenerPlanMejora() {
  const props = PropertiesService.getScriptProperties();
  const registros = PLAN_MEJORA_2026_2027.map(function(r) {
    const id = r[0];
    let seguimiento = {};
    try { seguimiento = JSON.parse(props.getProperty('PM_SEG_' + id) || '{}'); } catch(e) {}
    return {
      ID:id, DIMENSION:r[1], CRITERIO:r[2], PROPOSITO:r[3],
      FECHA_INICIO:r[4], FECHA_TERMINO:r[5], ANIO:r[4].slice(0,4),
      ACTIVIDAD:r[6], META:r[7], INDICADOR:'', CRITERIO_LOGRO:r[8],
      EVIDENCIA:r[9], RECURSOS:r[10], RESPONSABLES:r[11], COSTO_MM:r[12],
      ESTADO:seguimiento.estado || '', AVANCE:seguimiento.avance || '',
      OBSERVACION:seguimiento.observacion || '', URL_EVIDENCIA:seguimiento.urlEvidencia || '',
      FECHA_ACTUALIZACION:seguimiento.fechaActualizacion || ''
    };
  });
  const uniq = a => [...new Set(a.filter(Boolean))].sort();
  return {
    registros:registros,
    estadosPermitidos:['No iniciada','Iniciada','En proceso','Demorada','Terminada','No realizada'],
    filtros:{
      dimensiones:uniq(registros.map(r=>r.DIMENSION)),
      criterios:uniq(registros.map(r=>r.CRITERIO)),
      propositos:uniq(registros.map(r=>r.PROPOSITO)),
      anos:uniq(registros.map(r=>r.ANIO)),
      responsables:uniq([].concat.apply([], registros.map(r=>r.RESPONSABLES.split('/').map(x=>x.trim()))))
    }
  };
}

function actualizarSeguimientoPlanMejora(id, cambios) {
  const existe = PLAN_MEJORA_2026_2027.some(r => r[0] === id);
  if (!existe) throw new Error('Actividad no encontrada: ' + id);
  const props = PropertiesService.getScriptProperties();
  const key = 'PM_SEG_' + id;
  let actual = {};
  try { actual = JSON.parse(props.getProperty(key) || '{}'); } catch(e) {}
  ['estado','avance','observacion','urlEvidencia'].forEach(k => {
    if (cambios && Object.prototype.hasOwnProperty.call(cambios,k)) actual[k] = cambios[k];
  });
  actual.fechaActualizacion = Utilities.formatDate(new Date(), Session.getScriptTimeZone() || 'America/Santiago', 'dd/MM/yyyy HH:mm');
  props.setProperty(key, JSON.stringify(actual));
  return {registro: obtenerPlanMejora().registros.find(r => r.ID === id)};
}

function obtenerPlanMejoraCsv() {
  const datos = obtenerPlanMejora().registros;
  const cols = ['ID','DIMENSION','CRITERIO','PROPOSITO','FECHA_INICIO','FECHA_TERMINO','ACTIVIDAD','META','CRITERIO_LOGRO','EVIDENCIA','RECURSOS','RESPONSABLES','ESTADO','AVANCE','OBSERVACION','URL_EVIDENCIA','FECHA_ACTUALIZACION'];
  const esc = v => '"' + String(v == null ? '' : v).replace(/"/g,'""') + '"';
  const contenido = [cols.join(';')].concat(datos.map(r => cols.map(c => esc(r[c])).join(';'))).join('\n');
  return {disponible:true, archivo:'plan_mejora_2026_2027.csv', contenido:contenido};
}
